### PR TITLE
Fixed default message formatter (closes #41)

### LINKED ISSUE #41: Allow custom global option to be passed as an option until core Mongoose issue resolved or better documented
Per an issue I filed at <https://github.com/Automattic/mongoose/issues/5534>, our current usage of the global is not going to work.  I am sending a PR in shortly to resolve this, and also update documentation until this issue is resolved.

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by matteodelabre** [comment]
Thanks for your help! As I understand this, it enables users to override the default message, something impossible when you use `mongoose.Error.messages.general.unique`? However, I can’t see the use case for having two ways of overriding the default (in the Schema and in the options). Do you have an example where this is useful?

**Comment by niftylettuce** [comment]
Correct.  I don't specify a message in my schema but want to modify a
global default so that's why.  Also we should still support a custom
message per schema prop because people may customize as they need.

**Comment by niftylettuce** [comment]
@matteodelabre can you take a look at this? ty

File: index.js [hunk 1]
```diff
@@ -56,9 +50,10 @@ function getIndexes(collection) {
  * @param {Collection} collection Mongoose collection.
  * @param {Object} values Hashmap containing data about duplicated values
  * @param {Object} messages Map fields to unique error messages
+ * @param {String} message Default message formatter string
  * @return {Promise.<ValidationError>} Beautified error message
  */
-function beautify(error, collection, values, messages) {
+function beautify(error, collection, values, messages, message) {
```
Comment (matteodelabre) [inline index.js]: I think we should rename `message` to `defaultMessage` to avoid confusion between the singular `message` and the plural `messages` variable.

File: README.md [hunk 2]
```diff
@@ -180,17 +180,35 @@ The `errors` attribute contains a list of all original values that failed the un
 
 ### Error messages
 
-By default, the `ValidatorError` message will be the formatted value of `mongoose.Error.messages.general.unique` (which is set automatically by this package if not already defined).
+By default, the `ValidatorError` message will be the formatted value of a String `options.message` (which is set automatically by this package if not already defined).
 
-The default value of `mongoose.Error.messages.general.unique` is ``"Path `{PATH}` ({VALUE}) is not unique."`` which adheres to [the Mongoose error message defaults](https://github.com/Automattic/mongoose/blob/master/lib/error/messages.js).
+The default value of `options.message` is ``"Path `{PATH}` ({VALUE}) is not unique."`` which adheres to [the Mongoose error message defaults](https://github.com/Automattic/mongoose/blob/master/lib/error/messages.js).
```
Comment (matteodelabre) [inline README.md]: If we are going to introduce more API surface, I think we should be extra-clear on when one mechanism for overriding the message should be used instead of the other one. Currently, I have the feeling that `options.message` and the custom message in the `unique` field might feel redundant to the users.

In my opinion, the main use for `options.message` is for when the plugin is used globally. If you want to, I can try to improve the docs after merging this PR. I think renaming `options.message` to `options.defaultMessage` will make things clearer (see below).

**Comment by niftylettuce** [comment]
@matteodelabre if I change `options.message` to `options.defaultMessage`, then we exceed the 100 character limit for the line here <https://github.com/matteodelabre/mongoose-beautiful-unique-validation/pull/42#discussion_r132336677>.  Also, I think that specifying the prefix `default` is a bit redundant considering these are default options.  Can we get this merged as-is and released?  You could always change later to whatever you'd like + update docs.  I just really need this and would rather not use my fork in my `package.json`.

**Comment by matteodelabre** [comment]
We can always wrap that line if it becomes too long. I don’t think it’s clear enough for users that these are default options. No worries, I will make those changes by myself. Will publish 7.0.0 soon after. Thanks for your help!

**Comment by matteodelabre** [comment]
What do you think?

**Comment by niftylettuce** [comment]
Looks good to me
